#!/bin/bash -l
#SBATCH -A uppmax2026-1-61
#SBATCH -p pelle
#SBATCH -c 2
#SBATCH -t 00:30:00
#SBATCH -J trim_sr_tapi0666
#SBATCH --mail-type=ALL
#SBATCH --output=%x.%j.out
# Load modules
module load Trimmomatic
# Your commands
trimmomatic PE -threads 2  \
   /proj/uppmax2026-1-61/Genome_Analysis/2_Zhou_2023/reads/genomics_chr3_data/chr3_illumina_R1.fastq.gz \
   /proj/uppmax2026-1-61/Genome_Analysis/2_Zhou_2023/reads/genomics_chr3_data/chr3_illumina_R2.fastq.gz \
   sr_trimm_out/R1_paired.fastq.gz sr_trimm_out/R1_unpaired.fastq.gz \
   sr_trimm_out/R2_paired.fastq.gz  sr_trimm_out/R2_unpaired.fastq.gz \
   ILLUMINACLIP:TruSeq3-PE.fa:2:30:10 MINLEN:50 SLIDINGWINDOW:4:20 LEADING:5 TRAILING:5
